import localFont from "next/font/local";
import "./globals.css";
import "/public/assets/icons/style.css";
import HomeContextProvider from "./context/homeContext.js";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import { routing } from "../../../i18n/routing";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children ,params }) {
  const {locale} = await params;
  if(!routing.locales.includes(locale)){
    notFound()
  }
  const messages = await getMessages()
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <HomeContextProvider><NextIntlClientProvider>{children}</NextIntlClientProvider></HomeContextProvider> */}
        <HomeContextProvider><NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider></HomeContextProvider>
      </body>
    </html>
  );
}
