import localFont from "next/font/local";
import "./globals.css";
import "/public/assets/icons/style.css";
import HomeContextProvider from "./context/homeContext.js";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import PusherProvider from "./context/PusherProvider";
import { ToastContainer } from "react-toastify";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params
}) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    // notFound();
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HomeContextProvider>
          <NextIntlClientProvider>
            <PusherProvider>
              {children}
              <ToastContainer />
            </PusherProvider>
          </NextIntlClientProvider>
        </HomeContextProvider>
      </body>
    </html>
  );
}
